spring:
  application:
    name: user-crud-ms
  datasource:
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update
  data:
    rest:
      basePath: /api

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_HOME}
server:
  port: 8080

logging:
  root:
    level: DEBUG
